version: '3'

services:
    mongo:
        restart: always
        image: mongo:4.0.0
        expose:
            - 27017
        ports:
            - 27017:27017
        volumes:
          - ./docker/mongo/data:/data/db
    rabbitmq:
        restart: always
        image: rabbitmq:alpine
        hostname: "wtc-rabbit"
        expose:
            - 5672
        ports:
            - 5672:5672
        volumes:
          - ./docker/rabbitmq/data:/var/lib/rabbitmq/mnesia
    frontend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
        entrypoint:
            - /web-entrypoint.sh
        network_mode: "host"
