version: '3'

services:
    nginx:
        restart: always
        image: nginx:1.11.6-alpine
        ports:
            - 8000:8000
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./django
    mongo:
        restart: always
        image: mongo:4.0.0
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
        links:
            - mongo
        entrypoint:
            - /django-entrypoint.sh
    frontend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
        links:
            - backend
        entrypoint:
            - /web-entrypoint.sh
    rabbitmq:
        restart: always
        image: rabbitmq:alpine
        hostname: "wtc-rabbit"
