version: '3'

services:
    postgres:
        restart: always
        image: postgres:9.5.4
        expose:
            - 5432
        ports:
            - 5433:5432
        volumes:
          - ./docker/postgres/data:/var/lib/postgresql
          - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    mongo:
        restart: always
        image: mongo:4.0.0
        expose:
            - 8081
        ports:
            - 8081:8081
        volumes:
          - ./docker/mongo/data:/data/db
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
    rabbitmq:
        restart: always
        image: rabbitmq:alpine
        hostname: "wtc-rabbit"
        expose:
            - 5672
        ports:
            - 5672:5672
        volumes:
          - ./docker/rabbitmq/data:/var/lib/rabbitmq/mnesia
    frontend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
        entrypoint:
            - /web-entrypoint.sh
        network_mode: "host"
