version: '2'

services:
    nginx:
        restart: always
        image: nginx:1.11.6-alpine
    postgres:
        restart: always
        image: postgres:9.5.4
        expose:
            - 5432
        volumes:
          - ./docker/postgres/data:/var/lib/postgresql
    mongo:
        restart: always
        image: mongo:4.0.0
        expose:
            - 8081
        volumes:
          - ./docker/mongo/data:/data/db
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
    web:
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
