# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prep',
            fields=[
                ('name', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('campaign', models.CharField(editable=False, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('name', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow, editable=False)),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
