# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
