# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflow_prep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(max_length=400, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowSiteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.Site')),
            ],
        ),
        migrations.AlterField(
            model_name='workflow',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflowsitestatus',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow'),
        ),
    ]
