# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-02 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_auto_20180801_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowsitestatus',
            name='site_workflow_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
