# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-02 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowsitestatus_site_workflow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
