# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-07 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_auto_20180802_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowsitestatus',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='workflows.Workflow'),
        ),
    ]
