# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_auto_20180807_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='prep',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
