# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_auto_20180820_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='prep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='workflows.Prep'),
        ),
    ]
