# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_auto_20180820_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflows.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSiteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=400)),
                ('task_workflow_name', models.CharField(max_length=400, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='workflows.Task')),
            ],
        ),
        migrations.RemoveField(
            model_name='workflowsitestatus',
            name='site',
        ),
        migrations.RemoveField(
            model_name='workflowsitestatus',
            name='workflow',
        ),
        migrations.AddField(
            model_name='prep',
            name='cpus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prep',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prep',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='WorkflowSiteStatus',
        ),
    ]
