# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_auto_20180821_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasksitestatus',
            name='dataset',
            field=models.CharField(max_length=2000),
        ),
    ]
