# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_auto_20180821_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksitestatus',
            name='task_workflow_name',
        ),
    ]
